server:
    port: 8000
spring:
  profiles:
    active: default
  application:
    name: hotelManagement
  r2dbc:
    url: r2dbc:postgresql://localhost:5001/hotel
    username: hotel
    password: password


logging:
  level:
#    io.r2dbc.postgresql.QUERY: DEBUG
    org.springframework.r2dbc.core: DEBUG