server:
    port: 8000
spring:
  profiles:
    active: default
  application:
    name: hotelManagement
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring
    username: hotel
    password: hotel
